#!/usr/bin/env bash
# Registers the tpcitcgapp:// URI handler so browser OAuth callbacks work.
# Can be re-run independently if the handler breaks.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/lib/common.sh"

load_state  # sets PROTON_VERSION, PROTON_ROOT, PROTON_BIN, WINE_PREFIX, GAME_EXE

# ── Write the handler script ───────────────────────────────────────────────────
step "Writing URI handler script to ${HANDLER_BIN}"
mkdir -p "$(dirname "$HANDLER_BIN")"

cat > "$HANDLER_BIN" <<HANDLER_SCRIPT
#!/usr/bin/env bash
# Auto-generated by register-handler.sh — do not edit manually.
# Invoked by the browser when it sees a tpcitcgapp:// URL.
# \$1 = the full tpcitcgapp://callback?code=... URL

set -euo pipefail

CALLBACK_URL="\${1:-}"
[[ -n "\$CALLBACK_URL" ]] || { echo "[ptcgl-handler] No URL provided" >&2; exit 1; }

export STEAM_COMPAT_CLIENT_INSTALL_PATH="${FAKE_STEAM_COMPAT}"
export STEAM_COMPAT_DATA_PATH="${PREFIX_PARENT}"
export WINE_CPU_TOPOLOGY="2:0,1"

exec "${PROTON_BIN}" run "${GAME_EXE}" "\$CALLBACK_URL"
HANDLER_SCRIPT

chmod +x "$HANDLER_BIN"
success "Handler script written"

# ── Write the .desktop file ────────────────────────────────────────────────────
step "Writing ${HANDLER_DESKTOP}"
mkdir -p "$(dirname "$HANDLER_DESKTOP")"

cat > "$HANDLER_DESKTOP" <<DESKTOP_FILE
[Desktop Entry]
Name=PTCGL URI Handler
Comment=Handles tpcitcgapp:// auth callbacks for Pokemon TCG Live
Exec=${HANDLER_BIN} %u
Type=Application
Terminal=false
NoDisplay=true
MimeType=x-scheme-handler/tpcitcgapp;
DESKTOP_FILE

# ── Register with xdg ─────────────────────────────────────────────────────────
step "Registering tpcitcgapp:// with xdg-mime"

if command -v update-desktop-database &>/dev/null; then
    update-desktop-database "${HOME}/.local/share/applications"
fi

xdg-mime default ptcgl-handler.desktop x-scheme-handler/tpcitcgapp \
    || die "xdg-mime registration failed. Is xdg-utils installed?"

success "URI handler registered"

# Verify
registered=$(xdg-mime query default x-scheme-handler/tpcitcgapp 2>/dev/null || true)
if [[ "$registered" == "ptcgl-handler.desktop" ]]; then
    success "Verified: tpcitcgapp:// → ptcgl-handler.desktop"
else
    warn "xdg-mime verification returned '${registered}' (expected 'ptcgl-handler.desktop')"
    warn "Login may require manual URL copy-paste (see README)."
fi
